<a href="https://colab.research.google.com/github/CatarinaL/ddosLogs/blob/master/ddos_logs_logit_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
!pip install category_encoders

import numpy as np
import pandas as pd
from scipy.io import arff
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import category_encoders as ce
from category_encoders.wrapper import PolynomialWrapper

In [35]:
#/content/drive/MyDrive/datasets/ddosLogs/final-dataset.arff
np.random.seed(123)
file = "/content/drive/MyDrive/datasets/ddosLogs/final-dataset.arff"

data, meta = arff.loadarff(file)
df = pd.DataFrame(data=data)
df.info

<bound method DataFrame.info of          SRC_ADD  DES_ADD  ...  LAST_PKT_RESEVED     PKT_CLASS
0           3.00    24.30  ...         50.021920     b'Normal'
1          15.00    24.15  ...         50.030211     b'Normal'
2          24.15    15.00  ...         50.060221  b'UDP-Flood'
3          24.90     9.00  ...         50.060098     b'Normal'
4          24.80     8.00  ...         50.061864     b'Normal'
...          ...      ...  ...               ...           ...
2160663    24.10    10.00  ...         50.040562     b'Normal'
2160664    24.12    12.00  ...         50.051067     b'Normal'
2160665     1.00    24.10  ...         50.013418     b'Normal'
2160666     5.00    24.50  ...         50.027339     b'Normal'
2160667    15.00    24.15  ...         50.030211     b'Normal'

[2160668 rows x 28 columns]>

In [36]:
df

SRC_ADD  DES_ADD  ...  LAST_PKT_RESEVED     PKT_CLASS
0           3.00    24.30  ...         50.021920     b'Normal'
1          15.00    24.15  ...         50.030211     b'Normal'
2          24.15    15.00  ...         50.060221  b'UDP-Flood'
3          24.90     9.00  ...         50.060098     b'Normal'
4          24.80     8.00  ...         50.061864     b'Normal'
...          ...      ...  ...               ...           ...
2160663    24.10    10.00  ...         50.040562     b'Normal'
2160664    24.12    12.00  ...         50.051067     b'Normal'
2160665     1.00    24.10  ...         50.013418     b'Normal'
2160666     5.00    24.50  ...         50.027339     b'Normal'
2160667    15.00    24.15  ...         50.030211     b'Normal'

[2160668 rows x 28 columns]

In [37]:
#decode byte strings to remove the "b" before the srting values at cols PKT_CLASS, NODE_NAME_FROM, NODE_NAME_TO, FLAGS, PKT_TYPE 
categoricals = ["NODE_NAME_FROM", "NODE_NAME_TO", "FLAGS", "PKT_TYPE", "PKT_CLASS"]

for categorical in categoricals:
  df[categorical] = df[categorical].apply(lambda x: x.decode('utf-8')).astype("category") 

df

SRC_ADD  DES_ADD  ...  LAST_PKT_RESEVED  PKT_CLASS
0           3.00    24.30  ...         50.021920     Normal
1          15.00    24.15  ...         50.030211     Normal
2          24.15    15.00  ...         50.060221  UDP-Flood
3          24.90     9.00  ...         50.060098     Normal
4          24.80     8.00  ...         50.061864     Normal
...          ...      ...  ...               ...        ...
2160663    24.10    10.00  ...         50.040562     Normal
2160664    24.12    12.00  ...         50.051067     Normal
2160665     1.00    24.10  ...         50.013418     Normal
2160666     5.00    24.50  ...         50.027339     Normal
2160667    15.00    24.15  ...         50.030211     Normal

[2160668 rows x 28 columns]

In [38]:
df.describe()
df.isnull().values.any()

False

In [40]:
intgs = ["SRC_ADD", "DES_ADD", "PKT_ID", "FROM_NODE", "TO_NODE", "FID"]
for intg in intgs:
  df2[intg] = df[intg].astype('int64')


In [41]:
df.dtypes


SRC_ADD                int64
DES_ADD                int64
PKT_ID                 int64
FROM_NODE              int64
TO_NODE                int64
PKT_TYPE            category
PKT_SIZE             float64
FLAGS               category
FID                    int64
SEQ_NUMBER           float64
NUMBER_OF_PKT        float64
NUMBER_OF_BYTE       float64
NODE_NAME_FROM      category
NODE_NAME_TO        category
PKT_IN               float64
PKT_OUT              float64
PKT_R                float64
PKT_DELAY_NODE       float64
PKT_RATE             float64
BYTE_RATE            float64
PKT_AVG_SIZE         float64
UTILIZATION          float64
PKT_DELAY            float64
PKT_SEND_TIME        float64
PKT_RESEVED_TIME     float64
FIRST_PKT_SENT       float64
LAST_PKT_RESEVED     float64
PKT_CLASS           category
dtype: object

copying the df to one with target dummy variable (y), leaving original intact 

In [51]:
df2 = df.copy()

X = df2.iloc[:, 0:-1]
y = df2.iloc[:, [-1]]

In [52]:
X

SRC_ADD  DES_ADD  ...  FIRST_PKT_SENT  LAST_PKT_RESEVED
0              3       24  ...        1.000000         50.021920
1             15       24  ...        1.000000         50.030211
2             24       15  ...        1.030045         50.060221
3             24        9  ...        1.030058         50.060098
4             24        8  ...        1.030054         50.061864
...          ...      ...  ...             ...               ...
2160663       24       10  ...        1.030013         50.040562
2160664       24       12  ...        1.030026         50.051067
2160665        1       24  ...        1.000000         50.013418
2160666        5       24  ...        1.000000         50.027339
2160667       15       24  ...        1.000000         50.030211

[2160668 rows x 27 columns]

In [53]:
y

PKT_CLASS
0           Normal
1           Normal
2        UDP-Flood
3           Normal
4           Normal
...            ...
2160663     Normal
2160664     Normal
2160665     Normal
2160666     Normal
2160667     Normal

[2160668 rows x 1 columns]

In [63]:
#split into test and training sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

#dummy variables w/ WoE
# polynomial encoder wrapper for selected categorical variables
enc = PolynomialWrapper(ce.WOEEncoder(cols=["NODE_NAME_FROM", "NODE_NAME_TO", "FLAGS", "PKT_TYPE"]))

# transform the datasets
training_numeric_df2 = enc.fit_transform(X_train, y_train)
testing_numeric_df2 = enc.transform(X_test)

training_numeric_df2.info()

/usr/local/lib/python3.6/dist-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/usr/local/lib/python3.6/dist-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/usr/local/lib/python3.6/dist-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
/usr/local/lib/python3.6/dist-packages/category_encoders/utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):


<class 'pandas.core.frame.DataFrame'>
Int64Index: 1512467 entries, 303819 to 305711
Data columns (total 39 columns):
 #   Column                     Non-Null Count    Dtype  
---  ------                     --------------    -----  
 0   SRC_ADD                    1512467 non-null  int64  
 1   DES_ADD                    1512467 non-null  int64  
 2   PKT_ID                     1512467 non-null  int64  
 3   FROM_NODE                  1512467 non-null  int64  
 4   TO_NODE                    1512467 non-null  int64  
 5   PKT_SIZE                   1512467 non-null  float64
 6   FID                        1512467 non-null  int64  
 7   SEQ_NUMBER                 1512467 non-null  float64
 8   NUMBER_OF_PKT              1512467 non-null  float64
 9   NUMBER_OF_BYTE             1512467 non-null  float64
 10  PKT_IN                     1512467 non-null  float64
 11  PKT_OUT                    1512467 non-null  float64
 12  PKT_R                      1512467 non-null  float64
 13  PKT_DELA

In [66]:
X_train_enc = training_numeric_df2
X_test_enc = testing_numeric_df2

X_test_enc

SRC_ADD  DES_ADD  ...  FLAGS_SIDDOS  PKT_TYPE_SIDDOS
2002322       24        8  ...     -0.000071        -3.015949
2136657       10       24  ...     -0.000071         0.962001
238378        11       24  ...     -0.000071         0.962001
2018992       11       24  ...     -0.000071        -3.386976
1607715        2       24  ...     -0.000071         0.962001
...          ...      ...  ...           ...              ...
1007230       24        4  ...     -0.000071        -3.015949
1876974       12       24  ...     -0.000071        -3.386976
1857490        0       24  ...     -0.000071         0.962001
642338        24        6  ...     -0.000071        -3.015949
1245336        0       24  ...     -0.000071         0.962001

[648201 rows x 39 columns]

In [69]:
#TODO normalize

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_enc)
X_test_scaled = scaler.fit_transform(X_test_enc)

In [70]:
X_test_scaled

array([[ 1.11952814, -1.19607929,  1.27748827, ..., -0.24040455,
        -0.019877  , -0.6964335 ],
       [-0.49851185,  0.71197053, -0.87051728, ..., -0.22056381,
        -0.019877  ,  1.28836133],
       [-0.38293756,  0.71197053,  0.35977584, ..., -0.25674982,
        -0.019877  ,  1.28836133],
       ...,
       [-1.6542547 ,  0.71197053,  0.28308765, ..., -0.24040455,
        -0.019877  ,  1.28836133],
       [ 1.11952814, -1.43458551, -0.88417198, ..., -0.24040455,
        -0.019877  , -0.6964335 ],
       [-1.6542547 ,  0.71197053, -0.64767624, ..., -0.25674982,
        -0.019877  ,  1.28836133]])

The “lbfgs”, “sag” and “newton-cg” solvers only support 
 regularization or no regularization, and are found to converge faster for some high-dimensional data. Setting multi_class to “multinomial” with these solvers learns a true multinomial logistic regression model, which means that its probability estimates should be better calibrated than the default “one-vs-rest” setting.

The “sag” solver uses Stochastic Average Gradient descent (see https://hal.inria.fr/hal-00860051/document). It is faster than other solvers for large datasets, when both the number of samples and the number of features are large.

In [73]:
#instantiate the model - multinomial w/ sag solver #TODO: fix, model is not converging
'''
TODO: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
array([[  1207,      0,     75,      0,      0],
       [    13, 581075,     60,      0,      0],
       [     0,    117,   1860,      0,      0],
       [     9,   2490,     88,   1222,      0],
       [     0,   5939,      0,      0,  54046]]) 
'''

logreg = LogisticRegression(solver='sag', C=0.05, multi_class='multinomial',
                          random_state=42)

# fit the model with data
logreg.fit(X_train_scaled, y_train)

#
y_pred=logreg.predict(X_test_scaled)

# import the metrics class
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


array([[  1207,      0,     75,      0,      0],
       [    13, 581075,     60,      0,      0],
       [     0,    117,   1860,      0,      0],
       [     9,   2490,     88,   1222,      0],
       [     0,   5939,      0,      0,  54046]])